### ISSUE TITLE
BIP148 update

### ISSUE THREAD

**Issue by shaolinfry** [UASF/bitcoin#11]
Because BIP9 is based on time not block height, it is necessary to account for a significant portion of hashrate leaving for something else. The BIP148 start time needs to be brought forward to Aug 1, allowing for the unlikely but possible scenario of up to 85% of the hashrate leaving. Doing so will ensure segwit activates no matter what. I will adjust the BIP and reference implementation. Please review it.

**Comment by shaolinfry** [comment]
The spec has been updated https://github.com/bitcoin/bips/blob/master/bip-0148.mediawiki#specification

**Comment by unofficialsegwituasf** [comment]
Just to make it clear (it took me a while to understand your comment): 

Normal SegWit activation takes 1916 blocks of activation time to get active. In case 85% of the hashrate is missing (fork,..), these 1916 blocks could take a reaaaallly long time to get mined. So to ensure that we have enough time to mine these 1916 blocks, OP proposed the change to start earlier.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Just to make it a bit clearer for everyone (it took me a while to understand your comment): 

Normal SegWit activation takes 1916 blocks of activation time to get active. In case 85% of the hashrate is missing (fork,..), these 1916 blocks could take a reaaaallly long time to get mined. So to ensure that we have enough time to mine these 1916 blocks, OP proposed the change to start earlier.

**Comment by shaolinfry** [comment]
Aug 1 gives 6 months for the BIP to deploy which is enough imo, and would account for a catastrophic 85% loss, (which is unrealistic - if it happens we have other problems to worry about...).

**Comment by UASF** [comment]
Thank you @shaolinfry. Looks like PR #12 update to the latest specifications. Currently under review.
