### ISSUE TITLE
After UASF code is properly vetted, provide deterministically-built binary for distribution.

### ISSUE THREAD

**Issue by Vaesper** [UASF/bitcoin#14]
See https://github.com/bitcoin/bitcoin/blob/master/doc/gitian-building.md

**Comment by UASF** [comment]
Yes, we are still looking for the best way to distribute binaries.

**Comment by Rav3nPL** [comment]
It is yours: https://bip148.org/ ?

**Comment by quentinlesceller** [comment]
No. Looks like it is associated with [this repo](https://github.com/magmaship/bip148org).

**Comment by mkwia** [comment]
Closing. Refer to #19.
