### ISSUE TITLE
Should we track and regularly update from upstream?

### ISSUE THREAD

**Issue by mkwia** [UASF/bitcoin#17]
This would reduce the diff to only UASF code. Please discuss.

**Comment by bikeangel** [comment]
I was about to write the same thing.
As a user of this repo, the smaller the diff is, the easier it is to rely on it. 
All the latest commits to keep track of the core repo begin to be an issue. 
It is unexpected.

**Comment by UASF** [comment]
Maybe we can make a UASF Bitcoin core 0.14 branch and regularly merge commits from upstream.
I had to revert PR #15 in order to make 0.3 release. Since we don't know if there will be change in BIP148 before 0.14.1, creating a new branch might be appropriate.

**Comment by bikeangel** [comment]
Isn't possible to take the last official release sources, Bitcoin Core 0.14.0 ( Tag v0.14.0rc3 if i'm right ), apply the UASF patch and stop there ?

**Comment by UASF** [comment]
You mean delete the repo, start over and make a "clean" fork?

**Comment by UASF** [comment]
Also the UASF is directly applied on v0.14.0. Not sure what you are referring to.

Diff can be see here https://github.com/bitcoin/bitcoin/compare/ccb47bf830...UASF:v0.14.0.uasfsegwit3

**Comment by bikeangel** [comment]
A clean fork using only the 0.14.0 sources + patch would be great.
Diff url would be https://github.com/bitcoin/bitcoin/compare/v0.14.0...UASF:v0.14.0.uasfsegwit3 
But others should probably confirm this.

**Comment by whitslack** [comment]
> Also the UASF is directly applied on v0.14.0.

False. The UASF branch is based at ccb47bf83036f60dbef04f90aa06dd0f9c1917ac, which is six commits ahead of the `v0.14.0` tag.

This caused me some confusion while I was trying to determine the minimal UASF changeset. Also confusing were the cherry-picks from upstream. IMHO, this whole thing needs to be squashed and rebased onto `v0.14.0` so it is very clear what it does and does not incorporate from upstream. Further, UASF should not be merging (and should *definitely* not be cherry-picking) unreleased commits from upstream, as this makes computation of a sensible patch impossible.

**Comment by mkwia** [comment]
I suggest that we should;
- not track individual commits
- ensure that the UASF branch is based on v0.14.0
- when a new release is published on bitcoin/bitcoin
  - no longer update UASF on old branches
  - ensure that the current UASF branch is based on the latest full release (**not** release candidates!)

**Comment by h0jeZvgoxFepBQ2C** [comment]
Maybe we should also create a new "0.14_uasf" branch and apply the BIP148 changeset there. I was also a bit confused about the latest changes here, before realizing that they were cherry picked from bitcoin/0.14. 

Any thoughts?

**Comment by quentinlesceller** [comment]
Okay guys, based on the previous answers, we will:

1. Create a new UASF branch based on v0.14.0 (0.14-BIP148). See PR #18 
2. Not track individual commits.
3. when a new release is published on bitcoin/bitcoin
       no longer update UASF on current UASF branch
       ensure that the current UASF branch is based on the latest full release (not release candidates!)

**Comment by quentinlesceller** [comment]
Closing.
