### ISSUE TITLE
Provide gitian signatures of core developers

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [UASF/bitcoin#19]
Hi,

It would be great if some core developers would be so kind to sign the UASF gitian builds, so we at least have the signature validation to ensure the builds are correct?

Paging @luke-jr, @petertodd, @laanwj, @sipa, @jonasschnelli, @TheBlueMatt

**Comment by laanwj** [comment]
No problem. Can you give repo+tag to build. and where to send the assert files?

**Comment by quentinlesceller** [comment]
Repo: https://github.com/uasf/bitcoin.
Tag: v0.14.1-uasfsegwit0.3.
You can send me the assert files to my email (see my GitHub profile) or upload it.

**Comment by luke-jr** [comment]
It would be simplest if the owner of the "UASF" group forks the gitian.sigs repo, so we can just push sigs there...

**Comment by quentinlesceller** [comment]
Done https://github.com/UASF/gitian.sigs.

**Comment by quentinlesceller** [comment]
I will refer to these files on the release page.

**Comment by quentinlesceller** [comment]
Updated. Closing.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Thank you very much guys!
