### ISSUE TITLE
Please start GPG-signing tags

### ISSUE THREAD

**Issue by laanwj** [UASF/bitcoin#26]
Just noticed that the tag `v0.14.2-uasfsegwit0.3` is not GPG signed, and neither is the merge-commit it points to.
Would be good to start doing this, as the auditability of the gitian build chain from source to executable depends on being able to authenticate the tag, too.

**Comment by quentinlesceller** [comment]
Tags are now GPG-signed. See `v0.14.2-uasfsegwit1.0`.
