### ISSUE TITLE
Error with RPC port 

### ISSUE THREAD

**Issue by Olliecad1** [UASF/bitcoin#29]
error: couldn't connect to server: unknown (code -1)
(make sure server is running and you are connecting to the correct RPC port)

Hello I got an error with the RPC port, i have port 8333 open for my pi and in the bitcoin.conf file i have rpcport=8332  

Bitcoin does run but crashes about once every 2 hours or so.

I hope you can solve it :)

**Comment by unsystemizer** [comment]
You run out of RAM and bitcoind crashes.

**Comment by Olliecad1** [comment]
Thank you !!! I have solved it by reinstalling the operating system onto my pi and its not crashing now :)
