### ISSUE TITLE
Gitian compatible tag name advice from Luke Jr.

### ISSUE THREAD

**Issue by UncleHunto** [UASF/bitcoin#3]
### Describe the issue

Luke Jr mentioned in the bitcoin core slack earlier:
"btw, whoever maintains the UASF repo: please don't use the / character in tag names - your can't build that with gitian :P 
Just call it v0.14.0.uasfsegwit1 or something"

**Comment by sneurlax** [comment]
I think the code in question is in line 101 [here](https://github.com/UASF/bitcoin/commit/8bada77e21558167490bc8b8327fd6d4cd8dc581)

**Comment by UASF** [comment]
Wasn't he referring to [the first release](https://github.com/UASF/bitcoin/releases/tag/0.14%2FBIP148) where tag name was "0.14/BIP148"? Tag name is now v0.14.0.uasfsegwit, see https://github.com/UASF/bitcoin/tree/v0.14.0.uasfsegwit.

**Comment by UncleHunto** [comment]
@UASF I think you may be right, about him referring to the first release. If that is the case, you could probably close this issue.

**Comment by UASF** [comment]
Issue closed.
