### ISSUE TITLE
Update release process to match new repo location

### ISSUE THREAD

**Issue by PRabahy** [UASF/bitcoin#38]
https://github.com/UASF/bitcoin/edit/0.14-BIP148/doc/release-process.md still points to https://github.com/bitcoin-core/gitian.sigs.git, https://github.com/bitcoin-core/bitcoin-detached-sigs.git, and https://github.com/bitcoin/bitcoin.git. It doesn't appear that there is a bitcoin-detached-sigs for this repo, so it might make sense to remove those parts of the documentation.

**Comment by PRabahy** [comment]
I'm not sure if this matters, but the files under https://github.com/UASF/bitcoin/tree/0.14-BIP148/contrib/gitian-descriptors also still appear to be pointing to the old repos.

**Comment by mkwia** [comment]
We intent to keep all of the documentation intact as in bitcoin/bitcoin,
