### ISSUE TITLE
patching stock 0.14.2 doesn't work as intended using compare

### ISSUE THREAD

**Issue by EagleTM** [UASF/bitcoin#39]
Why doesn't 
https://github.com/bitcoin/bitcoin/compare/v0.14.2...UASF:0.14-BIP148.patch
or
https://github.com/bitcoin/bitcoin/compare/0.14...UASF:0.14-BIP148
apply cleanly against stock 0.14.2 ?

There are rejects for 
2 out of 2 hunks ignored -- saving rejects to file src/net_processing.cpp.rej
1 out of 1 hunk ignored -- saving rejects to file src/validation.h.rej
1 out of 1 hunk ignored -- saving rejects to file src/net.h.rej
5 out of 5 hunks ignored -- saving rejects to file src/net_processing.cpp.rej
1 out of 1 hunk ignored -- saving rejects to file src/init.cpp.rej
1 out of 1 hunk ignored -- saving rejects to file src/net.cpp.rej
1 out of 1 hunk ignored -- saving rejects to file src/net.h.rej

which are already applied in stock 0.14.2, which I found a bit odd. What is UASF:0.14-BIP148 based on and is there a clean patch to apply?

**Comment by unsystemizer** [comment]
It seems to me the "you can compare" links in each release suggest to apply vs 0.14.0

![image](https://user-images.githubusercontent.com/13134193/28487831-b9b694a4-6ecc-11e7-974c-e2a14c2d75c8.png)

**Comment by EagleTM** [comment]
Thanks, this is what I used
https://github.com/bitcoin/bitcoin/compare/0.14...UASF:0.14-BIP148
Which gives me 17 files changed, with the failures (already applied patches) above.

**Comment by luke-jr** [comment]
I'm pretty sure the reason is related to some patches being merged twice with two different commit hashes. Not much we can do to fix this, but `git diff` should work.

**Comment by EagleTM** [comment]
@luke-jr : Thanks for the insight. That explains it.  Patching with BIP91 is sufficient now, right so we don't actually need to patch BIP148 anymore (other than for uacomment maybe?) ?

**Comment by luke-jr** [comment]
For miners, I would recommend BIP148 modified for BIP91's height. For users, I recommend BIP148 for now.

**Comment by EagleTM** [comment]
How come you recommend BIP148 for users? The pull request for core is for BIP91 only?
Interstingly enough
https://github.com/bitcoin/bitcoin/compare/0.14...achow101:early-uasf-bip91.patch 
applies cleanly on the BIP148 branch. Is there any reason not to run both at the same time?

**Comment by luke-jr** [comment]
Either BIP91 or BIP148 is dangerous to run in a minority-user configuration. If Core merges BIP91-compatibility, then it is likely to be adopted by many users, and at that point makes sense for  BIP148 users to switch as well. But at the moment, the market support is almost entirely BIP148 among users, and disrupting that for no reason wouldn't be smart.

IOW, 60% BIP148, 40% nothing is better than 30% BIP91, 30% BIP148, 40% nothing. But 60% BIP91, 10% BIP148, 30% nothing would be best.

**Comment by EagleTM** [comment]
Thanks, I take it there is nothing wrong with doing something along the lines of https://www.reddit.com/r/Bitcoin/comments/6oyjic/howto_compile_bitcoin_core_with_bip91_and_bip148/

I'll close for now.
