### ISSUE TITLE
user agent

### ISSUE THREAD

**Issue by shaolinfry** [UASF/bitcoin#5]
I'm writing this without endorsing the binaries being offered with this project.

I think if you want to customize the user-agent, I would prefer explicitly stating BIP148 support e.g. `/Satoshi:0.14.0/BIP148:0/` rather than `UASF-Segwit`. BIP148 is designed to cause activation in all existing NODE_WITNESS nodes and while it is a class of UASF, it is very different to what a new user-activated soft fork would look like.

Obviously this is your project I can only offer my recommendation. But I would also hold off on deploying new code until BIP148 has had a bit more review.

**Comment by UASF** [comment]
Thank you for your comments @shaolinfry .

I agree with you for the user agent. I initially changed it to "UASF-Segwit" as a previous BIP148 fork used this denomination and he would be easier to see them under the same name on Bitnodes.

Code base is paused (except if a important bug like the previous one is discovered). I agree with you, this is an experimental release and it's just a way for the community to show support for your BIP148.

**Comment by UASF** [comment]
PR #7 changed user agent to "/Satoshi:0.14.0(UASF-Segwit 0.1; BIP148)/". That way node running this code still appears in Bitnodes with Bitcoin Knots and there is the mention of BIP148.

EDIT:
Reverted because of #8

**Comment by UASF** [comment]
Solved by #10.
